---
title: "Tuning GBM"
author: "Joshua Burkhart"
date: "March 7, 2016"
output: 
  pdf_document: 
    fig_width: 9
    fig_height: 6
    latex_engine: xelatex
---
# BMI 651: Tuning GBM

```{r global_options, echo=FALSE, include=FALSE, error=FALSE}
knitr::opts_chunk$set(
  fig.path = "Figs/",
  message = FALSE,
  warning = FALSE,
  include = TRUE,
  echo = TRUE,
  error = TRUE,
  fig.width = 11,
  comment = NA
)
```

```{r, echo=FALSE, include=FALSE}
library(MASS)
library(plyr) #this must be loaded before dplyr
library(dplyr)
library(ggplot2)
library(broom)
library(knitr)
library(magrittr)
library(reshape2)
library(infotheo)
library(stats)
library(car)
library(e1071)
library(bnlearn)
library(elmNN)
library(gbm)
library(stats)
set.seed(2013)
```

### Load Data

```{r}
setwd("~/SoftwareProjects/bmi_551_651_final/JoshBeta")

# gene id cols, cell line rows
expression <-
  read.table(
    "../data/expression.tsv",header = TRUE,sep = "\t",quote = "",row.names =
      1,check.names = FALSE,stringsAsFactors = FALSE
  )

# subtype cols, cell line rows
subtypes <-
  read.table(
    "../data/subtypes.txt",header = TRUE,sep = "\t",row.names = 1,check.names =
      TRUE
  )
subtypes[,1] <- subtypes[,1] %>% as.numeric()

# drug cols, cell line rows
training.classes <-
  t(
    read.table(
      "../data/training_set_answers.txt",header = TRUE,sep = "\t",check.names = FALSE
    )
  )
training.classes[,1:ncol(training.classes)] <-
  training.classes[,1:ncol(training.classes)] %>% as.numeric()

# Usage, id, drug, cell line columns, values in rows
scoring_and_test_set_id_mappings <-
  read.table(
    "../data/scoring_and_test_set_id_mappings.csv",header = TRUE,sep = ",",check.names =
      FALSE
  )

# organize subtypes, expression, train, test, classes...
sae <- rbind(data.frame(t(subtypes),check.names = FALSE),expression)

# split training data and kaggle holdout
training.features <- sae[,colnames(training.classes)]
kaggle.features <-
  sae[setdiff(colnames(sae),colnames(training.classes))]
```

### Scan for missing Data

```{r}
sum(is.na(training.features))
sum(is.na(kaggle.features))

sum(is.na(training.classes))
```

### Wilcoxon Rank Sum

```{r}
x.all_features = vector()

if(FALSE){
  for (drug_idx in 1:nrow(training.clas5ses))
  {
    training.features_train <- training.features
    training.classes_train <- training.classes[drug_idx,]
    
    ### Wilcoxan Rank Sum (Univariate Nonparametric Filter) for x dataset
    print(c('Wilcoxan Rank Sum: ',drug_idx))
    
    x.P_LIM = .01
    x.train_w_idx = vector()
    x.train_p_val = vector()
    
    for (i in 1:nrow(training.features_train)) {
      x.w <-
        wilcox.test(unlist(training.features_train[i,]) ~ training.classes_train, data =
                      training.features_train)
      if (x.w$p.value < x.P_LIM) {
        x.train_w_idx <-append(x.train_w_idx,i)
        x.train_p_val <- append(x.train_p_val,x.w$p.value)
      }
    }
    x.all_features <- union(x.all_features,x.train_w_idx)
  }
}
```

### Training and Kaggle Sets

```{r}
kaggle.classes <- data.frame()

x.all_features <- c(327,428,436,583,824,830,886,1240,1257,1260,1265,2717,3010,3507,3872,3977,4008,4541,4640,4765,4798,4848,4982,5105,5577,5971,6008,6062,6094,7149,7174,7272,7880,8036,8223,8701,8814,9040,9657,9667,9966,10214,10480,10551,10812,11621,12165,12187,12249,12451,12634,12872,12897,13090,13636,13832,13966,13995,14367,14421,14520,14921,15210,15679,15971,16294,16336,16922,17219,17293,17446,17522,17756,7,11,34,99,125,129,137,141,149,186,190,196,216,233,236,241,254,295,333,346,354,361,372,393,406,442,453,456,461,467,496,510,516,527,569,572,646,678,683,684,696,704,722,776,788,790,798,799,810,826,865,867,900,941,969,985,1007,1017,1047,1061,1073,1083,1084,1085,1086,1087,1103,1166,1170,1202,1254,1300,1301,1331,1381,1400,1416,1434,1441,1468,1480,1511,1566,1569,1586,1593,1597,1624,1637,1638,1651,1654,1697,1721,1758,1769,1811,1815,1825,1827,1834,1842,1862,1888,1895,1898,1916,1935,1939,1964,1965,1970,1980,1983,1989,2029,2058,2059,2061,2073,2083,2100,2101,2119,2134,2154,2160,2200,2296,2303,2305,2331,2333,2374,2380,2419,2434,2442,2454,2461,2462,2472,2513,2534,2542,2548,2558,2604,2611,2643,2651,2654,2656,2662,2679,2690,2691,2693,2705,2720,2725,2750,2774,2789,2791,2796,2807,2815,2819,2844,2852,2862,2891,2900,2907,2910,2914,2942,2956,2985,3004,3007,3018,3021,3101,3104,3128,3183,3185,3219,3252,3281,3284,3294,3297,3390,3393,3413,3449,3453,3458,3527,3532,3626,3631,3642,3647,3680,3711,3735,3747,3760,3764,3776,3790,3822,3865,3880,3903,3927,3963,4016,4027,4080,4122,4135,4142,4150,4157,4163,4203,4209,4211,4217,4233,4238,4271,4321,4325,4339,4356,4358,4391,4457,4463,4468,4480,4519,4526,4527,4534,4555,4564,4582,4597,4634,4651,4662,4667,4679,4687,4735,4763,4773,4776,4782,4835,4867,4873,4879,4884,4894,4897,4925,4950,5033,5045,5050,5059,5061,5080,5089,5091,5098,5139,5165,5167,5189,5198,5245,5247,5253,5266,5298,5311,5370,5372,5380,5445,5447,5456,5464,5556,5573,5579,5600,5636,5664,5679,5686,5729,5748,5769,5818,5846,5872,5876,5880,5882,5889,5897,5901,5903,5911,5913,5934,5962,5982,6015,6029,6038,6053,6058,6091,6095,6111,6117,6122,6160,6222,6259,6260,6278,6314,6326,6331,6332,6352,6353,6360,6381,6390,6398,6404,6405,6494,6508,6572,6577,6587,6589,6604,6620,6641,6657,6669,6671,6678,6727,6847,6857,6876,6879,6899,6937,6955,6977,6990,6993,7001,7048,7071,7103,7136,7159,7192,7193,7196,7199,7219,7241,7254,7256,7279,7284,7285,7292,7329,7388,7401,7415,7426,7470,7505,7510,7533,7542,7546,7565,7566,7577,7579,7591,7605,7622,7679,7685,7692,7696,7706,7719,7730,7732,7748,7790,7796,7826,7829,7851,7852,7854,7869,7881,7888,7909,7913,7939,7942,7943,7949,7956,8032,8038,8045,8064,8094,8115,8116,8139,8234,8252,8271,8317,8352,8365,8369,8372,8379,8391,8497,8517,8518,8529,8558,8594,8601,8615,8628,8638,8639,8651,8691,8700,8739,8744,8784,8794,8854,8859,8864,8883,8923,8928,8946,9032,9055,9059,9088,9124,9136,9139,9155,9188,9219,9220,9251,9254,9271,9281,9283,9326,9337,9350,9351,9354,9365,9396,9399,9403,9426,9459,9520,9528,9533,9566,9593,9633,9675,9687,9704,9714,9745,9760,9765,9786,9834,9838,9847,10004,10011,10022,10023,10071,10073,10110,10137,10150,10163,10174,10212,10217,10227,10229,10258,10265,10372,10400,10408,10431,10432,10467,10469,10481,10486,10521,10537,10539,10592,10692,10715,10772,10786,10796,10805,10829,10845,10854,10867,10898,10916,10971,10987,11000,11016,11035,11036,11037,11041,11099,11103,11170,11176,11177,11198,11212,11221,11238,11242,11252,11255,11257,11269,11270,11299,11301,11304,11310,11317,11334,11352,11386,11390,11402,11414,11428,11430,11432,11465,11474,11495,11509,11511,11533,11537,11567,11584,11616,11660,11683,11702,11708,11736,11746,11782,11805,11813,11865,11873,11881,11884,11885,11894,11900,11902,11907,11922,11928,11943,11972,11983,11988,11993,12032,12033,12037,12038,12053,12058,12063,12070,12125,12130,12133,12227,12283,12334,12345,12347,12348,12395,12404,12422,12428,12448,12472,12483,12488,12513,12521,12534,12540,12551,12557,12569,12644,12663,12698,12732,12777,12784,12795,12835,12869,12913,12914,12919,12956,12973,12983,12991,13009,13011,13019,13075,13135,13162,13177,13196,13204,13251,13268,13269,13277,13309,13323,13356,13364,13367,13368,13400,13435,13461,13483,13484,13491,13493,13504,13505,13506,13516,13541,13547,13568,13579,13584,13590,13592,13608,13624,13643,13649,13665,13666,13672,13676,13677,13684,13687,13701,13711,13728,13736,13795,13814,13875,13884,13888,13895,13902,13925,13934,13965,13972,13980,13994,14017,14028,14035,14068,14077,14081,14083,14087,14101,14124,14177,14182,14186,14198,14215,14218,14255,14263,14265,14268,14275,14309,14330,14354,14364,14407,14408,14415,14441,14443,14457,14474,14488,14537,14550,14572,14640,14688,14694,14711,14759,14776,14778,14794,14799,14811,14815,14837,14852,14874,14889,14924,14941,14955,15006,15022,15148,15154,15168,15185,15187,15206,15224,15230,15264,15266,15296,15330,15343,15350,15353,15357,15379,15380,15392,15401,15405,15407,15424,15425,15440,15457,15462,15466,15489,15497,15519,15548,15551,15566,15571,15574,15588,15695,15747,15786,15813,15825,15829,15884,15887,15906,15941,15964,15966,16033,16039,16069,16077,16115,16203,16229,16293,16313,16316,16327,16331,16371,16391,16419,16430,16435,16439,16460,16465,16474,16497,16511,16535,16598,16618,16702,16720,16727,16728,16738,16739,16748,16801,16981,17017,17023,17045,17083,17108,17138,17181,17184,17192,17195,17223,17234,17251,17254,17282,17284,17316,17346,17450,17458,17468,17483,17497,17510,17511,17539,17559,17562,17566)

x.all_features <- c(x.all_features,17603,17627,17628,17670,17683,17685,17729,17743,17744,17763,17767,17826,17830,17852,17892,17902,17911,17942,17949,17951,17972,17978,17979,17985,18063,18086,18088,18101,18104,18112,18114,18121,18124,18186,18196,18223,18234,18243,18254,18267,18281,18308,18310,18333,18347,18355,18365,18377,18379,18409,18412,18487,18499,18521,18538,18544,18549,18552,18558,18598,18624,8,12,17,20,29,36,43,54,69,78,82,93,96,109,126,143,160,177,247,252,261,283,284,294,307,323,356,370,373,380,384,386,426,454,464,466,489,504,530,582,586,599,603,612,625,652,654,664,680,737,740,744,837,840,924,943,949,950,991,1023,1032,1036,1046,1054,1063,1069,1078,1106,1114,1126,1131,1138,1155,1172,1185,1191,1226,1227,1246,1273,1275,1277,1278,1281,1284,1295,1297,1310,1326,1336,1342,1347,1351,1375,1418,1432,1435,1439,1460,1485,1496,1518,1523,1580,1585,1595,1598,1629,1633,1636,1665,1675,1718,1727,1739,1761,1763,1768,1781,1783,1785,1791,1799,1805,1814,1823,1829,1843,1872,1873,1881,1948,1949,1950,1951,1952,1957,1968,1979,1999,2000,2004,2052,2125,2141,2152,2153,2167,2168,2188,2197,2203,2207,2221,2226,2239,2269,2297,2315,2360,2392,2427,2463,2482,2489,2491,2495,2507,2515,2549,2561,2573,2580,2586,2595,2599,2621,2629,2645,2646,2652,2684,2716,2754,2769,2795,2810,2823,2845,2846,2849,2855,2859,2869,2921,2928,2940,2944,2953,2984,2991,3013,3049,3057,3071,3073,3077,3091,3092,3100,3102,3109,3124,3127,3140,3176,3178,3182,3196,3197,3217,3253,3275,3298,3308,3310,3316,3322,3330,3345,3350,3398,3415,3428,3441,3455,3456,3460,3462,3466,3484,3485,3553,3562,3578,3579,3650,3685,3691,3695,3744,3755,3761,3797,3798,3804,3817,3863,3888,3893,3974,3990,4073,4115,4155,4162,4166,4167,4173,4179,4210,4213,4234,4235,4259,4274,4283,4287,4304,4312,4326,4402,4428,4448,4455,4459,4494,4499,4505,4516,4522,4533,4552,4565,4579,4583,4594,4626,4632,4635,4656,4658,4677,4707,4708,4709,4710,4712,4725,4741,4753,4777,4797,4801,4812,4813,4837,4844,4881,4887,4920,4922,4955,4965,4971,4990,4996,5020,5035,5081,5087,5096,5122,5129,5144,5152,5166,5176,5195,5196,5205,5209,5213,5218,5241,5250,5269,5294,5295,5305,5319,5381,5403,5408,5418,5436,5459,5471,5472,5480,5490,5495,5496,5500,5533,5552,5554,5564,5567,5574,5599,5614,5629,5635,5650,5657,5661,5663,5672,5689,5693,5710,5711,5713,5717,5722,5725,5739,5753,5761,5762,5775,5779,5783,5786,5793,5807,5826,5867,5870,5887,5896,5988,5994,6050,6061,6076,6078,6079,6100,6103,6104,6113,6128,6140,6162,6167,6170,6171,6178,6182,6203,6204,6211,6230,6235,6241,6267,6273,6275,6276,6287,6308,6312,6323,6333,6403,6475,6509,6533,6536,6563,6568,6600,6601,6614,6632,6666,6676,6688,6696,6697,6701,6702,6723,6730,6736,6743,6776,6786,6832,6834,6842,6850,6856,6875,6882,6893,6909,6911,6953,6958,6974,6987,7007,7023,7024,7035,7036,7037,7038,7053,7058,7059,7073,7081,7087,7094,7117,7127,7137,7148,7165,7166,7177,7178,7189,7212,7227,7240,7243,7260,7264,7275,7305,7309,7313,7327,7378,7383,7391,7410,7418,7432,7436,7452,7468,7488,7503,7506,7520,7528,7539,7559,7590,7621,7633,7644,7659,7678,7690,7712,7716,7725,7751,7761,7769,7778,7782,7793,7806,7808,7815,7817,7849,7870,7898,7899,7908,7916,7930,7950,7958,7961,7964,7971,7975,8003,8040,8042,8058,8062,8093,8123,8137,8143,8150,8179,8183,8188,8194,8199,8202,8209,8224,8259,8264,8265,8266,8272,8280,8287,8291,8308,8320,8321,8330,8350,8356,8357,8389,8414,8432,8506,8527,8568,8571,8577,8581,8582,8589,8590,8599,8613,8620,8626,8666,8669,8679,8686,8692,8719,8720,8735,8743,8789,8800,8803,8811,8824,8825,8837,8843,8869,8874,8879,8909,8924,8942,8949,8960,8972,8982,8997,9001,9009,9012,9028,9029,9036,9044,9047,9052,9053,9067,9070,9073,9175,9183,9186,9193,9199,9205,9224,9240,9243,9357,9381,9404,9429,9433,9474,9476,9492,9537,9575,9617,9643,9670,9682,9689,9694,9737,9757,9769,9818,9828,9868,9890,9895,9898,9906,9917,9922,9931,9936,9962,9973,9978,9981,9987,9991,10035,10045,10053,10056,10060,10061,10086,10092,10103,10114,10156,10158,10160,10168,10198,10209,10219,10228,10249,10251,10270,10285,10295,10303,10310,10326,10348,10349,10358,10378,10401,10410,10419,10422,10426,10438,10444,10472,10478,10479,10507,10508,10515,10517,10523,10540,10555,10570,10578,10625,10633,10637,10646,10667,10677,10686,10700,10701,10720,10731,10735,10745,10749,10758,10763,10785,10798,10825,10835,10841,10882,10914,10938,10944,10955,10975,10979,10981,11017,11047,11050,11061,11063,11079,11091,11110,11111,11112,11114,11129,11156,11167,11193,11196,11217,11245,11261,11290,11294,11307,11313,11340,11355,11360,11413,11441,11451,11459,11466,11516,11519,11540,11552,11580,11581,11588,11598,11600,11628,11637,11644,11648,11650,11654,11680,11744,11749,11751,11761,11781,11812,11820,11824,11832,11859,11871,11909,11915,11950,12012,12027,12069,12078,12118,12120,12177,12182,12185,12191,12226,12228,12237,12243,12258,12275,12284,12305,12317,12327,12397,12402,12423,12435,12449,12450,12460,12465,12476,12523,12524,12541,12543,12565,12577,12596,12604,12661,12668,12682,12701,12708,12724,12738,12766,12770,12791,12814,12829,12838,12842,12843,12867,12878,12895,12927,12928,12940,12945,12949,12969,12980,13006,13014,13025,13068,13085,13138,13144,13155,13157,13180,13186,13194,13208,13216,13228,13237,13248,13270,13279,13291,13298,13303,13322,13325,13370,13394,13397,13423,13428,13447,13451,13454,13469,13472,13486,13510,13511,13526,13540,13578,13588,13606)

x.all_features <- c(x.all_features,13640,13645,13668,13674,13688,13689,13690,13692,13693,13695,13704,13753,13758,13759,13769,13772,13808,13817,13822,13823,13880,13882,13926,13931,13932,13956,13960,13996,14019,14025,14030,14063,14071,14079,14093,14139,14145,14156,14165,14178,14181,14192,14195,14201,14220,14222,14230,14240,14243,14246,14271,14288,14305,14310,14312,14318,14347,14349,14397,14399,14401,14414,14422,14436,14460,14464,14472,14475,14486,14525,14533,14543,14555,14567,14594,14595,14599,14625,14627,14635,14665,14675,14691,14693,14701,14724,14748,14753,14755,14764,14784,14790,14798,14812,14832,14840,14842,14861,14888,14898,14942,14950,14972,14973,14975,14978,14984,14988,15003,15005,15032,15048,15055,15064,15076,15088,15091,15096,15099,15151,15156,15172,15201,15233,15241,15272,15280,15333,15339,15346,15351,15366,15391,15402,15406,15435,15456,15556,15573,15577,15584,15611,15618,15624,15649,15668,15724,15746,15748,15752,15773,15789,15804,15821,15822,15839,15844,15894,15919,15926,15938,15946,15979,16004,16006,16029,16035,16036,16044,16047,16123,16150,16160,16169,16170,16171,16174,16181,16205,16230,16237,16239,16241,16250,16253,16254,16258,16262,16276,16286,16290,16296,16337,16359,16365,16376,16381,16389,16404,16441,16446,16503,16533,16542,16557,16584,16585,16590,16608,16610,16616,16621,16622,16624,16646,16660,16680,16682,16687,16694,16704,16755,16772,16773,16782,16784,16785,16810,16818,16843,16870,16874,16887,16912,16917,16918,16955,16967,16997,17009,17039,17090,17092,17107,17115,17118,17141,17166,17168,17212,17221,17243,17264,17269,17272,17289,17332,17365,17384,17386,17392,17393,17425,17437,17466,17471,17501,17507,17533,17592,17593,17598,17606,17607,17619,17626,17630,17638,17680,17702,17706,17719,17724,17742,17796,17823,17840,17854,17874,17906,17915,17956,18026,18030,18035,18046,18060,18097,18111,18125,18139,18170,18172,18199,18201,18210,18212,18220,18233,18247,18266,18288,18322,18346,18353,18383,18386,18411,18432,18448,18456,18483,18491,18495,18496,18520,18539,18556,18561,18584,18590,18613,18616,18629,199,208,397,1219,2274,2361,2686,2879,3017,3042,3062,3280,3791,4212,4445,4470,4685,4921,5334,5776,5964,6176,6561,6805,6851,6898,6945,6962,6996,7494,7662,8010,8482,8668,8769,9146,9253,9316,10149,10382,10412,10628,10879,11329,11508,11780,12183,12244,12267,12533,12636,12953,13431,13517,13720,13801,14170,14646,14721,15354,15698,16073,16208,16226,16718,17178,17632,18204,18208,18260,18593,10,49,64,71,80,237,249,296,324,522,637,762,809,901,1009,1010,1022,1051,1081,1104,1171,1210,1484,1506,1568,1599,1605,1659,1689,1720,1817,1922,1937,2008,2075,2133,2146,2165,2183,2294,2376,2559,2632,2851,3067,3135,3158,3239,3328,3518,3524,3548,3592,3601,3648,3660,3732,3782,3818,3827,3832,3925,4014,4084,4089,4183,4385,4422,4478,4502,4636,4762,4779,4979,5150,5255,5353,5369,5446,5549,5582,5613,5720,5794,5997,6007,6016,6026,6143,6195,6202,6215,6336,6339,6610,6654,6658,6799,7075,7135,7139,7182,7474,7646,7694,7727,7728,7765,7853,7885,7955,8022,8051,8055,8078,8190,8261,8276,8351,8399,8523,8552,8654,8878,8907,8920,8965,9005,9128,9164,9228,9259,9289,9405,9443,9484,9503,9546,9561,9621,9663,9990,10082,10091,10159,10178,10363,10413,10421,10425,10464,10482,10492,10552,10636,10651,10682,10734,10755,10846,10892,11065,11148,11165,11223,11300,11302,11417,11449,11549,11610,11924,12106,12195,12278,12308,12311,12387,12400,12635,12677,12722,12726,12793,12820,12841,12861,12921,12992,13192,13429,13576,13577,13626,13667,13800,13856,13899,13923,13939,13981,13984,14024,14102,14129,14252,14260,14359,14374,14470,14473,14535,14552,14592,14634,14643,14659,14705,14746,14839,15028,15065,15067,15142,15257,15285,15358,15371,15400,15427,15436,15530,15542,15557,15560,15719,15987,16187,16193,16221,16264,16281,16298,16302,16330,16338,16457,16566,16604,16679,16767,16854,17002,17117,17176,17235,17275,17338,17356,17408,17481,17519,17520,17549,17611,17650,17713,17764,17804,17910,17925,18003,18064,18090,18091,18102,18173,18191,18218,18222,18224,18263,18339,18370,18413,18423,18453,18468,18542,18612,1,2,147,185,214,234,303,363,374,417,537,635,672,756,953,1016,1031,1120,1159,1183,1190,1198,1217,1266,1286,1430,1445,1448,1529,1531,1557,1639,1759,1766,1790,1847,1867,1907,1923,1941,2002,2033,2067,2139,2218,2321,2339,2356,2364,2411,2412,2437,2459,2473,2516,2536,2539,2552,2702,2721,2741,2749,2763,2766,2808,2824,2829,2835,2908,3002,3011,3031,3060,3075,3078,3106,3201,3226,3288,3343,3401,3406,3446,3451,3474,3525,3533,3656,3671,3682,3690,3698,3736,3743,3781,3853,3894,3897,4000,4180,4182,4230,4484,4485,4491,4580,4584,4587,4605,4697,4699,4721,4739,4740,4792,4926,4962,5066,5088,5112,5155,5162,5340,5513,5530,5532,5561,5575,5604,5645,5647,5666,5696,5715,5782,5829,5847,5853,5878,5888,5925,5974,6006,6019,6049,6063,6166,6214,6296,6346,6411,6449,6500,6576,6580,6619,6639,6655,6656,6680,6752,6811,6867,6877,6906,7032,7052,7110,7133,7170,7179,7200,7234,7290,7317,7323,7384,7399,7463,7500,7508,7557,7581,7594,7620,7711,7848,7858,7860,7889,7929,7968,7978,7979,8016,8046,8082,8121,8160,8196,8235,8278,8304,8368,8380,8386,8515,8637,8641,8660,8676,8716,8899,8903,8915,8937,8948,8957,8979,9020,9097,9114,9115,9227,9236,9300,9341,9378,9394,9411,9420,9442,9515,9527,9545,9559,9565,9590,9608,9640,9658,9703,9796,9819,9839,9840,9862,9896,9947,10016,10036,10055,10081,10177,10225,10275,10277,10434,10489,10535,10611,10618,10629,10659,10671,10680,10746,10768,10808,10837,10877,10881,10899,11027,11083,11089,11233,11249,11268,11326,11335,11419,11435,11447,11478,11498,11536,11555,11559,11569,11620,11656,11663,11664,11707,11731,11740,11766,11768,11783,11860)

x.all_features <- c(x.all_features,11989,12044,12090,12126,12131,12146,12151,12152,12170,12190,12232,12234,12309,12333,12405,12491,12589,12602,12646,12657,12690,12734,12754,12778,12873,12947,12950,12974,12989,13038,13054,13118,13127,13143,13166,13185,13328,13337,13383,13410,13415,13520,13534,13561,13610,13614,13627,13641,13651,13703,13721,13734,13761,13835,13858,13905,13915,13982,13998,14001,14023,14044,14088,14097,14164,14193,14205,14206,14272,14306,14446,14461,14465,14577,14616,14826,14862,14893,14913,14914,14920,14946,14956,15020,15035,15108,15115,15119,15129,15158,15212,15228,15331,15356,15563,15567,15591,15603,15617,15665,15726,15795,15849,15867,15872,15921,15952,16018,16146,16173,16183,16204,16222,16408,16413,16418,16463,16518,16558,16581,16603,16632,16638,16666,16670,16692,16707,16821,16827,16866,16868,16932,17024,17099,17114,17172,17191,17277,17318,17387,17401,17431,17433,17485,17503,17514,17529,17531,17583,17616,17665,17666,17681,17710,17720,17730,17746,17803,17813,17818,17819,17856,17882,17920,17980,18024,18055,18081,18103,18141,18176,18232,18238,18272,18341,18361,18382,18394,18467,18469,18477,18488,18498,18504,18516,18555,18576,18578,18621,18632,31,39,41,68,174,187,224,272,322,332,334,343,350,376,383,388,409,473,494,507,566,577,618,640,667,688,689,712,716,760,766,807,833,864,866,871,872,897,904,919,956,965,982,990,1092,1105,1107,1200,1231,1244,1259,1289,1318,1333,1382,1397,1457,1459,1491,1510,1548,1572,1657,1664,1686,1687,1693,1722,1777,1788,1854,1870,1874,1908,1918,1954,1984,1994,2005,2037,2048,2065,2096,2105,2177,2219,2249,2278,2403,2410,2440,2458,2478,2522,2553,2555,2568,2569,2585,2601,2602,2603,2626,2661,2692,2701,2713,2738,2776,2798,2840,2848,2875,2965,2971,3001,3008,3009,3036,3037,3050,3056,3074,3095,3136,3147,3174,3207,3248,3305,3334,3386,3436,3488,3573,3700,3705,3739,3740,3769,3773,3783,3794,3809,3819,3840,3851,3870,3883,3909,3919,3959,3969,3980,4047,4114,4138,4144,4187,4189,4202,4224,4244,4246,4256,4258,4374,4401,4458,4551,4559,4614,4628,4645,4646,4673,4701,4726,4785,4888,4892,4895,4896,4931,4988,5120,5178,5280,5302,5343,5458,5469,5502,5558,5594,5608,5615,5637,5641,5676,5687,5695,5743,5766,5778,5806,5843,5850,6067,6147,6258,6304,6306,6341,6349,6385,6424,6483,6497,6539,6550,6570,6685,6749,6761,6782,6790,6848,6849,6853,6858,6864,6889,6896,7020,7068,7083,7108,7120,7167,7202,7269,7294,7328,7361,7369,7374,7428,7472,7479,7515,7555,7563,7573,7604,7638,7717,7780,7799,7838,7896,7900,7934,7938,7980,7985,7996,8000,8039,8068,8087,8128,8151,8156,8164,8254,8262,8343,8408,8429,8439,8443,8496,8545,8596,8605,8642,8673,8684,8695,8747,8797,8892,8922,8947,8952,9030,9125,9126,9207,9257,9325,9388,9392,9453,9486,9500,9507,9519,9607,9652,9671,9683,9713,9721,9762,9790,9795,9802,9803,9831,9875,9877,9891,9900,9956,9960,9984,10008,10021,10028,10127,10191,10208,10244,10293,10377,10380,10437,10528,10569,10577,10598,10614,10639,10647,10661,10723,10762,10848,10851,10869,10896,10897,10919,10924,10953,11072,11092,11116,11136,11139,11146,11147,11155,11171,11189,11191,11229,11234,11244,11276,11287,11322,11333,11381,11404,11405,11431,11454,11456,11458,11485,11492,11545,11576,11685,11721,11741,11745,11786,11798,11844,11883,11932,11978,11981,12018,12051,12089,12114,12153,12184,12192,12201,12209,12219,12257,12269,12313,12322,12358,12381,12412,12463,12536,12563,12595,12598,12616,12669,12681,12756,12779,12794,12797,12868,12920,12936,12958,12961,12972,12990,12999,13033,13073,13081,13082,13094,13114,13149,13176,13223,13262,13273,13359,13407,13457,13465,13479,13482,13521,13536,13571,13582,13602,13623,13639,13646,13683,13876,13886,13889,13973,13975,13993,14005,14018,14040,14050,14051,14055,14067,14084,14110,14128,14134,14153,14158,14232,14279,14283,14301,14345,14360,14366,14370,14371,14379,14416,14427,14434,14452,14484,14501,14514,14573,14597,14611,14617,14622,14652,14666,14716,14737,14875,14908,14919,14932,14953,14980,14990,15025,15071,15074,15110,15143,15165,15216,15244,15284,15291,15369,15385,15459,15473,15488,15537,15545,15565,15622,15632,15686,15700,15776,15787,15841,15875,15892,15909,15986,16010,16054,16138,16210,16235,16236,16246,16274,16323,16467,16482,16484,16490,16500,16552,16620,16635,16658,16741,16747,16756,16758,16766,16768,16770,16808,16823,16833,16884,16906,17028,17105,17120,17169,17171,17208,17230,17233,17245,17256,17259,17345,17420,17438,17467,17512,17548,17561,17563,17587,17605,17629,17664,17674,17750,17785,17875,17948,17970,17997,18072,18144,18155,18171,18183,18188,18251,18259,18324,18426,18510,18529,18537,18548,18585,18602,18607,18,24,25,53,111,142,165,180,184,202,230,243,259,265,274,280,290,293,308,331,341,360,411,422,441,445,448,459,509,540,564,579,588,629,648,653,656,700,735,747,755,757,772,796,797,802,815,828,842,876,887,888,895,898,905,906,921,923,935,945,952,957,979,989,998,1004,1015,1025,1050,1052,1058,1062,1066,1109,1137,1145,1152,1167,1192,1197,1213,1288,1294,1298,1299,1302,1311,1316,1317,1348,1357,1358,1359,1360,1361,1389,1391,1412,1422,1423,1442,1443,1449,1477,1502,1505,1515,1528,1535,1551,1578,1581,1649,1650,1660,1669,1678,1690,1695,1698,1711,1723,1731,1733,1756,1767,1803,1820,1837,1845,1864,1865,1877,1886,1890,1896,1897,1911,1930,1932,1936,1940,1988,1991,2015,2035,2040,2045,2056,2076,2077,2079,2097,2098,2099,2104,2108,2109,2161,2186,2187,2202,2204,2206,2211,2220,2252,2254,2255,2256,2261,2283,2316,2322,2323,2362,2373,2383,2385,2388,2398,2399,2422,2443,2486,2502,2503,2545)

x.all_features <- c(x.all_features,2583,2589,2591,2596,2600,2605,2624,2637,2639,2640,2663,2683,2688,2697,2698,2708,2710,2722,2723,2729,2739,2772,2800,2802,2804,2833,2838,2854,2857,2861,2865,2895,2911,2925,2937,2961,2962,2970,2977,2982,2994,3014,3019,3022,3045,3059,3119,3161,3162,3194,3206,3213,3238,3260,3276,3285,3293,3314,3331,3349,3360,3365,3366,3378,3389,3397,3422,3433,3442,3501,3534,3539,3555,3557,3566,3583,3596,3611,3617,3619,3639,3640,3653,3658,3661,3664,3684,3723,3733,3738,3748,3768,3774,3787,3802,3837,3841,3861,3882,3884,3911,3918,3930,3940,3941,3948,3960,3981,3988,4007,4017,4019,4043,4065,4069,4081,4091,4103,4105,4112,4121,4141,4149,4156,4164,4193,4208,4215,4219,4221,4227,4237,4239,4240,4245,4247,4265,4290,4292,4293,4299,4316,4331,4338,4346,4359,4369,4379,4397,4416,4419,4444,4473,4493,4529,4546,4586,4613,4618,4629,4648,4649,4678,4696,4715,4731,4744,4755,4757,4769,4786,4799,4805,4826,4840,4846,4852,4869,4900,4913,4917,4961,4966,4976,4986,4997,4998,5016,5017,5019,5026,5032,5037,5040,5062,5073,5093,5125,5134,5140,5156,5174,5208,5271,5281,5282,5291,5321,5330,5333,5347,5352,5355,5356,5359,5360,5361,5365,5409,5411,5432,5439,5487,5491,5497,5504,5512,5518,5562,5563,5581,5592,5624,5627,5667,5678,5683,5697,5709,5721,5768,5784,5787,5796,5801,5802,5823,5824,5851,5857,5871,5875,5885,5890,5905,5912,5916,5928,5932,5947,5976,6042,6052,6065,6069,6083,6115,6136,6144,6150,6163,6180,6188,6212,6252,6298,6359,6373,6375,6376,6393,6401,6409,6410,6421,6427,6436,6439,6455,6473,6477,6479,6496,6506,6540,6547,6556,6562,6565,6575,6578,6586,6613,6616,6637,6662,6668,6693,6729,6731,6734,6744,6748,6763,6766,6783,6795,6810,6827,6912,6917,6918,6978,6984,7010,7018,7019,7030,7033,7040,7061,7066,7092,7095,7116,7155,7205,7207,7223,7226,7267,7295,7319,7321,7324,7339,7340,7352,7387,7409,7434,7442,7444,7454,7455,7477,7490,7526,7531,7535,7547,7549,7551,7568,7571,7592,7599,7606,7613,7619,7649,7680,7691,7699,7707,7714,7718,7757,7770,7773,7774,7776,7820,7824,7828,7834,7846,7855,7862,7868,7884,7915,7917,7918,7981,7993,8004,8041,8054,8069,8080,8081,8101,8103,8108,8141,8207,8210,8220,8233,8242,8243,8245,8283,8290,8292,8296,8302,8331,8337,8340,8364,8381,8385,8392,8394,8437,8438,8442,8452,8458,8459,8461,8463,8477,8491,8492,8494,8508,8509,8524,8542,8548,8556,8559,8563,8573,8591,8609,8610,8621,8636,8643,8671,8689,8746,8753,8755,8777,8782,8793,8799,8805,8807,8819,8839,8855,8860,8865,8871,8876,8902,8905,8910,8917,8925,8978,8990,8996,9008,9024,9031,9037,9061,9081,9112,9122,9167,9170,9191,9214,9215,9225,9239,9263,9268,9308,9319,9334,9345,9363,9372,9440,9451,9481,9508,9511,9542,9551,9574,9580,9598,9603,9609,9610,9614,9620,9626,9647,9648,9660,9666,9680,9697,9698,9700,9718,9720,9734,9735,9764,9784,9785,9798,9804,9809,9812,9820,9865,9882,9886,9905,9908,9919,9923,9926,9928,9959,9964,9972,9974,9977,9983,10003,10041,10105,10119,10123,10140,10145,10147,10179,10193,10210,10218,10235,10247,10260,10274,10290,10296,10301,10325,10354,10362,10368,10392,10394,10398,10405,10415,10417,10424,10430,10433,10441,10446,10453,10494,10497,10531,10541,10543,10550,10553,10558,10571,10572,10583,10590,10603,10607,10615,10617,10631,10642,10660,10683,10687,10714,10717,10721,10747,10756,10769,10770,10794,10801,10803,10804,10819,10820,10844,10858,10861,10875,10883,10889,10893,10905,10935,10960,10991,11002,11010,11026,11039,11049,11056,11058,11060,11068,11075,11098,11108,11115,11117,11125,11130,11145,11164,11169,11180,11181,11183,11206,11209,11214,11231,11232,11239,11248,11275,11282,11286,11305,11316,11330,11346,11362,11368,11380,11382,11421,11439,11445,11476,11477,11520,11531,11534,11538,11543,11551,11603,11612,11614,11619,11631,11662,11690,11699,11709,11715,11729,11748,11762,11763,11765,11778,11785,11793,11806,11818,11835,11841,11843,11858,11861,11874,11876,11895,11896,11912,11926,11927,11933,11940,11965,11974,12011,12043,12097,12103,12127,12150,12178,12188,12211,12236,12254,12255,12271,12335,12361,12371,12390,12394,12408,12445,12447,12457,12492,12496,12499,12504,12506,12532,12555,12556,12582,12611,12620,12622,12639,12670,12688,12697,12702,12741,12747,12752,12768,12780,12807,12819,12821,12827,12828,12832,12852,12854,12871,12881,12912,12922,12934,12960,12977,12988,13004,13008,13018,13059,13060,13074,13105,13117,13126,13136,13150,13152,13165,13168,13172,13175,13201,13205,13218,13236,13242,13243,13244,13254,13256,13266,13267,13284,13292,13319,13331,13342,13343,13346,13365,13369,13372,13376,13389,13404,13416,13419,13460,13462,13463,13464,13480,13485,13497,13509,13515,13528,13535,13548,13551,13552,13563,13565,13585,13598,13621,13630,13655,13663,13664,13682,13699,13705,13707,13715,13732,13733,13799,13837,13865,13866,13869,13873,13877,13898,13907,13908,13930,13943,13971,13976,13977,13997,14003,14004,14008,14012,14034,14074,14111,14114,14136,14143,14150,14185,14189,14204,14235,14245,14270,14274,14284,14290,14291,14300,14315,14317,14320,14343,14357,14369,14372,14387,14389,14391,14409,14410,14442,14449,14466,14506,14538,14589,14602,14614,14615,14644,14663,14692,14695,14731,14734,14745,14756,14780,14791,14806,14835,14844,14848,14876,14877,14909,14928,14929,14949,14970,14981,14994,15001,15012,15041,15044,15061,15063,15077,15079,15081,15089,15098,15106,15118,15130,15136,15139,15163,15166,15199,15234,15254,15258,15259,15261,15262,15270,15276,15282,15294,15324,15397,15414,15449,15507,15511,15532,15535,15552,15553,15554,15562,15568,15579,15587,15608,15645,15648,15650,15667,15671,15677,15714,15736,15760,15770,15780,15790,15801,15806,15824,15830,15831,15832,15835)

x.all_features <- c(x.all_features,15845,15848,15863,15869,15873,15886,15888,15893,15922,15949,15965,15967,15982,16005,16028,16034,16051,16067,16068,16071,16075,16078,16126,16131,16137,16151,16152,16162,16177,16206,16215,16233,16244,16247,16249,16259,16334,16342,16366,16367,16372,16374,16382,16386,16388,16390,16396,16411,16431,16433,16442,16453,16454,16455,16469,16473,16477,16478,16480,16481,16485,16496,16524,16534,16538,16543,16544,16574,16578,16580,16586,16588,16627,16650,16677,16689,16693,16697,16709,16740,16742,16759,16763,16769,16774,16788,16790,16792,16800,16814,16826,16831,16846,16858,16867,16873,16876,16897,16921,16938,16943,16952,16958,16959,16964,17008,17027,17031,17041,17062,17064,17067,17068,17072,17075,17096,17106,17121,17127,17134,17158,17188,17197,17228,17247,17253,17257,17260,17266,17268,17290,17300,17305,17320,17322,17327,17343,17351,17354,17366,17385,17413,17430,17434,17459,17461,17462,17465,17516,17518,17524,17527,17536,17538,17547,17574,17597,17623,17657,17673,17675,17676,17679,17695,17696,17697,17703,17704,17705,17708,17727,17731,17751,17753,17766,17777,17790,17792,17821,17857,17858,17886,17890,17913,17916,17924,17931,17936,17946,17952,17958,17962,17967,17968,17973,17974,17991,17999,18011,18016,18077,18092,18098,18117,18165,18203,18209,18211,18229,18230,18249,18268,18282,18292,18300,18302,18309,18311,18332,18378,18402,18417,18439,18466,18473,18485,18486,18563,18573,18582,18600,18620,18633,4,164,183,319,481,641,759,785,822,977,1013,1024,1026,1056,1127,1161,1242,1274,1296,1420,1436,1509,1588,1606,1627,1642,1744,1749,1774,1893,1931,1987,1990,2094,2341,2432,2444,2576,2715,2801,2816,2820,2853,2885,2898,2926,2955,2986,3107,3125,3263,3400,3429,3464,3473,3481,3580,3581,3586,3689,3722,3734,3825,3945,4032,4079,4216,4243,4300,4348,4408,4451,4536,4558,4620,4719,4742,5044,5060,5164,5182,5227,5263,5429,5543,5646,5681,5685,5708,5726,5972,6005,6060,6073,6151,6242,6310,6348,6408,6471,6528,6538,6583,6611,6636,6659,6689,6691,6773,6825,6855,6878,6942,6964,6986,7015,7140,7144,7191,7233,7242,7258,7315,7367,7422,7441,7453,7529,7596,7658,7731,7750,7763,7767,7832,7910,7927,7936,8018,8031,8065,8120,8147,8195,8211,8238,8344,8464,8533,8670,8717,8756,8826,8846,8884,8890,8893,8995,9003,9086,9100,9111,9140,9213,9299,9366,9473,9539,9624,9631,9642,9693,9728,9858,9946,10046,10080,10304,10330,10334,10353,10375,10391,10455,10475,10562,10630,10716,10722,10775,10800,10821,10868,10901,10921,10929,10946,10983,11078,11140,11211,11319,11332,11523,11579,11585,11667,11758,11772,11784,11801,11848,11890,11966,12014,12141,12189,12203,12303,12403,12458,12515,12591,12662,12664,12687,12691,12717,12911,13077,13096,13128,13274,13299,13332,13340,13591,13617,13741,14000,14009,14127,14224,14324,14352,14382,14393,14420,14444,14618,14642,14689,14700,14713,14768,14779,14989,15004,15029,15036,15133,15155,15164,15209,15319,15338,15450,15637,15640,15659,15731,15754,15837,16009,16024,16090,16118,16124,16216,16227,16272,16362,16401,16425,16471,16523,16540,16556,16568,16569,16582,16617,16628,16651,16663,16778,16813,16857,16860,16909,16993,17026,17053,17119,17129,17156,17249,17252,17288,17325,17406,17411,17464,17558,17589,17634,17644,17653,17739,17752,17782,17917,17975,18146,18156,18174,18192,18371,18389,18401,18422,18447,18564,19,27,48,161,312,366,415,433,536,620,720,733,746,765,767,780,800,829,853,869,913,996,1035,1044,1118,1168,1187,1188,1340,1475,1476,1520,1537,1556,1703,1705,1724,1741,1747,1838,2006,2026,2031,2038,2060,2140,2245,2253,2270,2304,2308,2347,2359,2393,2575,2612,2616,2675,2782,2821,2822,2825,2918,2932,2981,2997,3134,3142,3166,3187,3202,3221,3237,3361,3430,3452,3491,3505,3547,3582,3585,3686,3812,3821,3874,3921,3926,4035,4106,4218,4263,4295,4383,4497,4523,4567,4593,4617,4619,4681,4684,4727,4728,4811,4822,4882,4991,5009,5046,5078,5086,5102,5124,5183,5184,5192,5259,5286,5324,5434,5511,5531,5541,5553,5565,5566,5583,5671,5716,5738,5773,5789,5862,5866,5894,5914,5924,5969,6043,6059,6071,6102,6174,6250,6277,6371,6387,6440,6468,6491,6574,6605,6608,6626,6670,6751,6758,6907,6959,7163,7168,7172,7265,7293,7392,7396,7439,7485,7492,7509,7543,7601,7632,7668,7674,7683,7786,7802,7850,7867,7928,7954,7963,7986,8015,8024,8029,8037,8117,8152,8293,8341,8342,8409,8428,8505,8532,8553,8674,8678,8707,8745,8763,8768,8781,8783,8861,8868,8900,8904,8926,8980,9007,9034,9079,9117,9153,9235,9265,9349,9360,9602,9627,9637,9668,9672,9725,9749,9768,9871,9961,9992,10089,10109,10113,10181,10186,10240,10241,10591,10616,10696,10782,10862,10912,10936,11034,11064,11070,11179,11227,11311,11314,11336,11408,11472,11521,11539,11558,11630,11670,11696,11788,11803,11817,11823,11830,11869,11882,11887,11914,11959,12028,12036,12091,12168,12252,12261,12281,12288,12323,12378,12382,12418,12479,12613,12633,12645,12660,12709,12719,12721,12737,12760,12782,12805,12812,12944,13012,13064,13069,13209,13306,13321,13334,13341,13360,13502,13555,13572,13609,13615,13722,13780,13827,13897,13936,14010,14094,14149,14151,14242,14258,14376,14429,14496,14650,14673,14760,14763,14773,14830,14887,14895,14902,14903,15038,15127,15152,15235,15251,15268,15367,15411,15418,15458,15469,15534,15540,15555,15602,15615,15619,15631,15666,15744,15763,15809,15879,16003,16011,16020,16046,16110,16165,16178,16283,16423,16428,16476,16516,16619,16649,16664,16696,16717,16722,16781,16840,16980,17073,17182,17236,17262,17278,17292,17326,17376,17407,17442,17445,17489,17506,17578,17671,17718,17810,17827,17859,17888,18010,18020,18041,18061,18078,18109,18205,18245,18270,18301,18323,18337,18395,18414,18430,18460,18502,18506,18610,18623,59,207,348,451,482,663,854,1102,1417,1421)

x.all_features <- c(x.all_features,1437,1555,1905,2041,2080,2386,2476,2734,2781,2841,2874,2909,3110,3439,3606,3737,3871,4072,4252,4289,4324,4466,4574,4716,4795,4941,5236,5337,5345,5424,5712,5910,5966,6010,6101,6377,6407,6532,6621,6733,6793,6863,7104,7326,7610,7636,7759,7764,7823,7905,7992,8180,8222,8295,8310,8395,8476,8741,8935,8970,9016,9108,9190,9272,9279,9339,9448,9587,9619,9677,9830,9979,9999,10019,10151,10207,10255,10407,10509,10514,10566,10843,10988,11009,11044,11256,11411,11643,11773,11816,12175,12220,12440,12789,12860,13311,13477,13575,13593,13622,13752,13789,14033,14053,14211,14217,14253,14432,14530,14532,14722,14802,14857,15448,15580,15674,15955,16130,16166,16353,16512,16612,16796,16838,16895,16925,16940,16956,16991,16995,17018,17843,18085,18100,18162,18296,18319,18470,395,501,806,882,1195,1255,1315,1410,1467,1499,1617,1836,1858,1912,2413,2866,2923,3198,3272,3629,4575,4664,4914,5231,5276,5425,5517,5746,5865,5886,6226,6232,6289,6707,6787,6982,7218,7297,7322,7425,7695,8316,8416,8538,8576,8616,8709,8787,8840,8962,9159,9458,9482,9564,9611,9712,9779,9816,10927,10934,11104,11298,11651,11693,11872,12132,12154,12166,12199,12421,12430,12505,12593,12692,12933,13214,13302,13653,13833,14016,14479,14580,14678,14881,14897,15056,15097,15180,15612,16008,16042,16405,16555,16600,16623,16990,17357,17374,17394,17865,18147,18327,18515)

#x.all_features <-
#  c(
#    2,7,8,20,29,41,69,129,143,149,186,187,190,196,207,233,241,243,252,274,283,284,295,307,346,350,354,370,373,376,406,415,433,448,454,459,481,510,516,522,527,530,564,566,572,653,680,683,689,712,722,735,747,757,767,788,790,798,799,810,826,828,830,842,864,865,867,888,900,904,945,952,956,969,979,985,990,1004,1010,1015,1016,1017,1023,1052,1056,1061,1062,1069,1083,1084,1085,1087,1106,1114,1120,1127,1131,1137,1138,1172,1185,1190,1213,1226,1231,1240,1244,1273,1284,1286,1300,1301,1311,1317,1318,1331,1342,1381,1422,1423,1439,1441,1459,1468,1477,1485,1496,1502,1511,1515,1556,1586,1595,1599,1636,1638,1659,1664,1665,1678,1690,1705,1721,1733,1741,1768,1774,1790,1814,1815,1823,1827,1834,1842,1843,1847,1854,1870,1872,1873,1877,1881,1886,1895,1896,1916,1918,1930,1948,1950,1965,1968,1970,1988,1989,1991,1994,2004,2037,2052,2058,2059,2060,2096,2097,2099,2100,2101,2141,2146,2152,2202,2204,2207,2218,2220,2226,2249,2252,2296,2322,2333,2347,2359,2362,2374,2376,2383,2419,2434,2442,2458,2482,2502,2503,2516,2522,2552,2558,2583,2595,2596,2611,2626,2629,2643,2652,2662,2663,2679,2683,2688,2690,2692,2693,2698,2710,2722,2738,2750,2776,2789,2795,2800,2804,2808,2815,2824,2829,2846,2848,2862,2865,2875,2891,2910,2928,2942,2962,2971,2985,3001,3004,3021,3036,3045,3059,3067,3073,3078,3101,3104,3127,3166,3174,3178,3194,3197,3198,3217,3248,3252,3253,3276,3281,3284,3285,3288,3293,3294,3298,3305,3310,3350,3386,3389,3390,3397,3401,3415,3430,3433,3439,3451,3453,3455,3456,3488,3491,3525,3534,3555,3557,3573,3578,3580,3596,3601,3626,3642,3653,3658,3661,3680,3684,3689,3695,3698,3737,3740,3743,3744,3747,3760,3773,3776,3781,3782,3783,3797,3802,3818,3819,3827,3840,3861,3865,3870,3874,3880,3882,3903,3918,3930,3940,3959,3960,3990,4027,4035,4089,4091,4138,4141,4142,4155,4156,4166,4182,4208,4209,4212,4216,4217,4227,4240,4244,4245,4256,4263,4274,4289,4290,4321,4326,4339,4358,4359,4369,4397,4416,4445,4463,4468,4473,4485,4494,4529,4533,4534,4546,4555,4558,4564,4579,4582,4594,4613,4634,4645,4656,4679,4685,4707,4715,4731,4755,4795,4799,4801,4805,4812,4813,4835,4840,4844,4846,4869,4873,4879,4882,4888,4896,4897,4900,4979,4988,5016,5026,5033,5066,5080,5081,5086,5091,5093,5125,5139,5140,5144,5164,5165,5176,5183,5192,5195,5198,5209,5218,5263,5266,5280,5291,5333,5361,5370,5372,5380,5381,5411,5418,5459,5464,5490,5496,5497,5500,5504,5517,5518,5533,5541,5553,5562,5563,5567,5574,5592,5604,5614,5615,5627,5635,5641,5657,5664,5667,5681,5687,5709,5713,5717,5729,5739,5775,5786,5787,5802,5806,5807,5818,5823,5851,5857,5862,5866,5867,5870,5872,5876,5882,5890,5896,5897,5905,5913,5914,5932,5934,5947,5971,6006,6007,6010,6038,6049,6060,6062,6073,6095,6101,6102,6111,6113,6163,6166,6167,6180,6212,6222,6287,6298,6331,6333,6346,6349,6376,6390,6398,6403,6404,6408,6409,6449,6473,6479,6496,6547,6556,6561,6563,6565,6572,6575,6587,6610,6613,6626,6637,6639,6662,6668,6669,6676,6696,6727,6731,6734,6743,6749,6786,6805,6842,6847,6857,6875,6876,6877,6889,6912,6974,6986,6996,7010,7018,7019,7020,7030,7032,7033,7036,7037,7038,7058,7066,7068,7075,7103,7116,7136,7137,7159,7189,7196,7199,7202,7207,7219,7223,7226,7234,7240,7256,7264,7267,7269,7295,7309,7329,7361,7367,7378,7392,7396,7401,7410,7415,7422,7426,7468,7472,7510,7520,7526,7531,7533,7535,7547,7559,7563,7566,7579,7605,7620,7622,7632,7636,7638,7646,7685,7690,7692,7696,7706,7711,7719,7725,7727,7730,7731,7732,7759,7770,7778,7780,7824,7828,7834,7838,7849,7854,7862,7880,7884,7896,7909,7916,7917,7939,7942,7943,7958,7964,7975,7980,7981,7985,7993,8004,8031,8032,8038,8039,8045,8062,8065,8081,8087,8094,8115,8128,8141,8156,8160,8164,8195,8224,8233,8245,8254,8266,8271,8272,8276,8278,8287,8308,8352,8365,8381,8392,8437,8461,8482,8497,8505,8517,8518,8542,8556,8558,8559,8563,8568,8573,8581,8582,8590,8594,8599,8615,8620,8628,8639,8651,8671,8674,8679,8700,8707,8709,8735,8741,8743,8746,8753,8777,8782,8784,8793,8819,8854,8864,8865,8869,8874,8879,8899,8904,8949,8990,8996,9005,9044,9047,9055,9059,9086,9108,9114,9124,9125,9128,9155,9164,9167,9188,9193,9207,9239,9268,9281,9308,9319,9326,9337,9345,9350,9354,9365,9396,9399,9404,9448,9459,9476,9492,9508,9511,9533,9537,9551,9624,9631,9633,9643,9660,9670,9672,9683,9687,9693,9704,9718,9745,9762,9765,9769,9790,9798,9812,9831,9834,9865,9871,9875,9890,9908,9919,9928,9947,9964,9973,9974,9979,10003,10004,10022,10035,10045,10053,10060,10073,10091,10145,10150,10156,10158,10174,10217,10219,10229,10235,10244,10265,10270,10296,10303,10353,10368,10408,10415,10422,10431,10434,10441,10444,10453,10489,10507,10517,10523,10531,10541,10551,10558,10571,10583,10591,10598,10615,10633,10636,10651,10667,10683,10687,10692,10714,10721,10734,10747,10762,10772,10785,10786,10794,10796,10801,10820,10837,10845,10846,10848,10854,10875,10879,10883,10893,10896,10898,10899,10912,10914,10919,10924,10935,10971,10979,10991,11016,11035,11039,11063,11068,11078,11079,11089,11099,11139,11147,11167,11169,11170,11176,11181,11189,11191,11196,11212,11227,11229,11231,11242,11244,11245,11252,11255,11257,11269,11276,11313,11330,11333,11334,11362,11382,11386,11390,11405,11414,11428,11431,11432,11445,11449,11456
#  )

#x.all_features <-
#  c(
#    x.all_features,11466,11472,11474,11477,11485,11509,11511,11516,11521,11537,11551,11552,11581,11584,11588,11614,11637,11650,11651,11670,11680,11693,11702,11708,11709,11736,11748,11763,11784,11812,11820,11832,11861,11865,11885,11894,11896,11909,11943,11966,11972,11981,11988,11989,11993,12018,12027,12033,12037,12044,12051,12058,12063,12078,12089,12133,12177,12182,12185,12209,12236,12237,12244,12249,12271,12275,12311,12333,12334,12348,12378,12422,12428,12458,12476,12488,12492,12496,12499,12506,12521,12524,12533,12536,12557,12569,12595,12620,12633,12635,12644,12661,12662,12668,12677,12690,12698,12701,12702,12708,12726,12732,12741,12770,12777,12778,12780,12782,12784,12795,12805,12821,12827,12835,12852,12854,12871,12881,12914,12919,12921,12940,12945,12947,12956,12972,12973,12983,12988,12999,13006,13008,13011,13014,13019,13068,13077,13105,13117,13135,13136,13152,13157,13165,13168,13172,13176,13185,13201,13204,13248,13268,13269,13279,13298,13303,13346,13369,13370,13376,13394,13400,13404,13428,13435,13454,13460,13465,13479,13480,13493,13504,13506,13517,13536,13547,13552,13563,13571,13588,13602,13606,13617,13621,13640,13643,13649,13665,13668,13672,13674,13682,13690,13703,13704,13705,13733,13734,13736,13759,13769,13795,13799,13817,13823,13833,13865,13877,13880,13888,13895,13915,13931,13932,13943,13966,13973,13977,13984,13993,13994,13995,14005,14010,14030,14035,14050,14051,14074,14077,14081,14083,14087,14102,14114,14124,14127,14143,14145,14156,14158,14164,14177,14182,14215,14218,14224,14230,14240,14245,14252,14263,14291,14305,14310,14315,14317,14318,14343,14347,14352,14389,14393,14407,14415,14427,14441,14457,14464,14466,14470,14474,14488,14496,14501,14555,14572,14573,14577,14595,14597,14615,14622,14634,14635,14644,14646,14652,14659,14663,14693,14722,14731,14753,14759,14760,14794,14811,14812,14815,14830,14844,14862,14877,14887,14889,14908,14909,14924,14941,14973,14975,15003,15005,15012,15022,15041,15063,15064,15106,15143,15148,15151,15152,15164,15165,15185,15201,15206,15224,15228,15234,15251,15266,15282,15285,15291,15296,15343,15367,15392,15401,15405,15407,15427,15435,15449,15466,15473,15519,15532,15534,15551,15552,15553,15560,15568,15571,15573,15611,15624,15637,15650,15667,15695,15719,15763,15790,15801,15806,15821,15824,15830,15835,15841,15873,15884,15887,15906,15921,15938,15941,15946,15949,15955,15965,15966,15982,16003,16004,16028,16034,16051,16115,16124,16131,16162,16166,16170,16181,16205,16206,16210,16216,16227,16233,16235,16246,16249,16259,16274,16276,16313,16316,16327,16362,16371,16376,16386,16404,16423,16425,16430,16433,16439,16465,16476,16477,16478,16480,16485,16497,16500,16503,16518,16534,16543,16566,16581,16585,16586,16598,16610,16651,16660,16679,16694,16738,16739,16748,16755,16759,16763,16773,16774,16778,16818,16821,16868,16874,16909,16912,16925,16932,16943,16952,16959,16980,17002,17009,17017,17018,17039,17075,17083,17092,17096,17099,17107,17108,17117,17134,17138,17156,17158,17169,17172,17181,17192,17197,17223,17251,17254,17257,17266,17275,17277,17284,17300,17305,17316,17354,17393,17425,17431,17458,17459,17497,17503,17518,17519,17520,17531,17533,17536,17548,17559,17562,17566,17578,17597,17603,17606,17623,17627,17628,17629,17638,17657,17666,17673,17676,17680,17685,17697,17703,17706,17708,17727,17743,17744,17750,17813,17821,17840,17888,17892,17924,17936,17949,17951,17956,17979,17997,18026,18063,18088,18091,18097,18101,18103,18109,18112,18121,18124,18125,18139,18170,18171,18172,18176,18196,18199,18201,18205,18211,18220,18223,18234,18247,18249,18251,18254,18267,18272,18288,18296,18310,18322,18324,18332,18333,18337,18353,18355,18377,18378,18383,18389,18394,18402,18411,18417,18439,18453,18466,18468,18469,18483,18491,18502,18521,18556,18590,18598,18613,18629,18633
#  )

training.features_train <- data.frame()
training.classes_train <- numeric()
x.cv_mhc <- NA
x.cv_err <- Inf
x.cv_elm <- NA
training.features_ncol <- numeric()
x.cv_boost <- numeric()
x.avg_err <- 1
x.dists <- vector()
x.lims <- vector()
x.SPLIT <- 0.8


for (drug_idx in 1:nrow(training.classes))
{
  training.features_train <- training.features
  training.classes_train <- training.classes[drug_idx,]
  
  ### Cross Validation Loop
  
  # variables to store loop results
  x.cv_mhc <- NA
  x.cv_err <- Inf
  x.cv_gbm <- NA
  training.features_ncol <-
    round(x.SPLIT * ncol(training.features_train))
  x.cv_boost <-
    rep(1 / ncol(training.features_train),ncol(training.features_train))
  x.tot_err <- vector()
  
  for (loop in 1:4) {
    ### Split Training & Validation sets with random sampling (Monte Carlo cross validation)
    
    # 5-fold Cross Validation
    index <-
      sample(
        1:ncol(training.features_train),training.features_ncol,replace = TRUE,prob = unlist(lapply(x.cv_boost,function(x){(abs(x)) / sum(abs(x.cv_boost))}))
      )
    
    training.features_train_cv <- training.features_train[,index]
    training.classes_train_cv <- training.classes_train[index]
    training.features_validation_cv <-
      training.features_train[,-index]
    training.classes_validation_cv <-
      training.classes_train[-index]
    
    tree_lim <- 500
    gbm_dist <- sample(c("poisson","bernoulli","gaussian","adaboost"))[mod(loop,4) + 1]
    
    if (x.all_features %>% length > 0)
    {
      x.all_features_cv <- x.all_features
      
      #now we can retain only our selected columns
      training.features_train_w <-
        training.features_train_cv[x.all_features_cv,]

      #add the class labels to the feature data frame
      training.train_gbm_input <-
        data.frame(t(training.features_train_w),check.names = FALSE)

      #train model
      x.model <-
        gbm.fit(
          x = training.train_gbm_input,y = training.classes_train_cv,n.minobsinnode = 2,distribution = gbm_dist,n.trees = tree_lim
        )

      ### Validation (on hold out data)
      
      #filter features
      training.validation_gbm_input <-
        data.frame(t(training.features_validation_cv[x.all_features_cv,]), check.names = FALSE)
      
      #test
      x.prediction_cv <- predict(x.model,training.validation_gbm_input,n.tree=tree_lim)
      
      x.class_ag <-
        table(round(lapply(x.prediction_cv,function(x) {ifelse(x < 0,0,ifelse(x > 1,1,x))})),training.classes_validation_cv) %>%
        classAgreement()
      
      #misclassification rate
      x.err_rate <- 1 - x.class_ag$diag
      
      #print(c('cv error rate:',x.err_rate))
      
      x.tot_err <- c(x.tot_err,x.err_rate)
      
      if (x.err_rate < x.cv_err) {
        x.cv_mhc <- x.all_features_cv
        x.cv_err <- x.err_rate
        x.cv_gbm <- x.model
        x.gbm_dist <- gbm_dist
        x.tree_lim <- tree_lim
      }
      
      if (x.err_rate == 0) {
        print("err_rate 0 reported, breaking out of loop...")
        break
      }
      
    }else{
      print(
        "Ignoring this cv loop because wilcoxon rank sum routine filtered all features from fold. Is the wilcoxon rank sum p-value set too low?"
      )
    }
    ### Boosting probabilities
    x.cv_boost[-index] <- x.cv_boost[-index] + abs(x.cv_err)
  }
  x.dists <- c(x.dists,x.gbm_dist)
  x.lims <- c(x.lims,x.tree_lim)
  x.avg_err <- c(x.avg_err,x.cv_err)
  
print(c("loop:",drug_idx,'min_err:', x.cv_err))
  
  ### Loop Results
  
  # markov blanket, & error rate
  #print(c(x.cv_mhc,"min cv error rate:",x.cv_err))
  
  ### Predict Kaggle Holdout
  
  #filter features
  kaggle.gbm_input <-
    data.frame(t(kaggle.features[x.cv_mhc,]), check.names = FALSE)
  
  #test
  kaggle.predictions <-
    predict(x.cv_gbm,kaggle.gbm_input,n.tree=x.tree_lim)
  
  kaggle.classes <- rbind(kaggle.classes,lapply(kaggle.predictions,function(x) {ifelse(x < 0,0,ifelse(x > 1,1,x))}))
}

rownames(kaggle.classes) <- rownames(training.classes)
colnames(kaggle.classes) <- colnames(kaggle.features)

kaggle.classes %>% str()
```

```{r}
mapping <- read.csv("../data/scoring_and_test_set_id_mappings.csv",check.names=FALSE)

kaggle.out <- data.frame()

for(row in 1:nrow(mapping))
{
  kaggle.out <- rbind(kaggle.out,c(mapping[row,"id"],kaggle.classes[mapping[row,"drug"],mapping[row,"cellline"]]))
}
colnames(kaggle.out)<-c('id','value')

fptr <- file(description="./tuningGBM_out.csv",'w')
write.csv(kaggle.out,fptr,row.names=FALSE, quote = FALSE)
close(fptr)

print(c("loop:",drug_idx,"avg_min_err:",sum(x.avg_err)/length(x.avg_err),"x.dists:",x.dists,"x.lims:",x.lims))
```
