---
title: "pamr"
author: "Mark"
date: "March 7, 2016"
output: 
  pdf_document: 
    fig_width: 9
    fig_height: 6
    latex_engine: xelatex
---
# BMI 651: PAmr

```{r global_options, echo=FALSE, include=FALSE, error=FALSE}
knitr::opts_chunk$set(
  fig.path = "Figs/",
  message = FALSE,
  warning = FALSE,
  include = TRUE,
  echo = TRUE,
  error = TRUE,
  fig.width = 11,
  comment = NA
)
```

```{r, echo=FALSE, include=FALSE}
library(MASS)
library(plyr) #this must be loaded before dplyr
library(dplyr)
library(ggplot2)
library(broom)
library(knitr)
library(magrittr)
library(reshape2)
library(infotheo)
library(stats)
library(car)
library(e1071)
library(bnlearn)
library(randomForest)
library(pamr)
set.seed(2013)
```

### Load Data

```{r}
#setwd("~/R/bmi_551_651_final")

# gene id cols, cell line rows
expression <-
  read.table(
    "~/R/bmi_551_651_final/data/expression.tsv",header = TRUE,sep = "\t",quote = "",row.names =
      1,check.names = FALSE,stringsAsFactors = FALSE
  )

# subtype cols, cell line rows
subtypes <-
  read.table(
    "~/R/bmi_551_651_final/data/subtypes.txt",header = TRUE,sep = "\t",row.names = 1,check.names =
      TRUE
  )
subtypes[,1] <- subtypes[,1] %>% as.numeric()

# drug cols, cell line rows
training.classes <-
  t(
    read.table(
      "~/R/bmi_551_651_final/data/training_set_answers.txt",header = TRUE,sep = "\t",check.names = FALSE
    )
  )
training.classes[,1:ncol(training.classes)] <-
  training.classes[,1:ncol(training.classes)] %>% as.numeric()

# Usage, id, drug, cell line columns, values in rows
scoring_and_test_set_id_mappings <-
  read.table(
    "~/R/bmi_551_651_final/data/scoring_and_test_set_id_mappings.csv",header = TRUE,sep = ",",check.names =
      FALSE
  )

# organize subtypes, expression, train, test, classes...
sae <- rbind(data.frame(t(subtypes),check.names = FALSE),expression)

# split training data and kaggle holdout
training.features <- sae[,colnames(training.classes)]
kaggle.features <-
  sae[setdiff(colnames(sae),colnames(training.classes))]
```

### Scan for missing Data

```{r}
sum(is.na(training.features))
sum(is.na(kaggle.features))

sum(is.na(training.classes))
```

### Training and Kaggle Sets

```{r}
kaggle.classes <- data.frame()

for (drug_idx in 1:nrow(training.classes))
{
  training.features_train <- data.frame(t(training.features), check.names = FALSE)
  training.classes_train <- training.classes[drug_idx,]
  kaggle.features <- data.frame(t(kaggle.features), check.names = FALSE)
  
}

rownames(kaggle.classes) <- rownames(training.classes)
colnames(kaggle.classes) <- colnames(kaggle.features)

kaggle.classes %>% str()
```

###Example Pamr analysis from HW3 using the eset object
```{r}
##########PAMr#############
#Classification using nearest shrunken centroid method
#########################
#use non feature selected data set
dat <- exprs(TRAIN)
#grab annotation 
gene_names <- featureData(TRAIN)$gene
gID <- featureNames(TRAIN)
sID <- sampleNames(TRAIN)
train.dat <- list(x = dat, y = labels, genenames = gene_names, geneid = gID,sampleid = sID)
#generate model and threshold values
pam_model <- pamr.train(train.dat)
pam_model

#compute cross validation error
pam_model.cv <- pamr.cv(pam_model, train.dat, nfold = 10)
#more reliable error estimate than misclassification rate
pam_model.cv

#plot the misclassification and cross validation error
pamr.plotcv(pam_model.cv)

#two best t-values according to c.v. and misclassification
t0 <- 2.335#823 features, 1 misclassification error, 1 cross validation error


#plot the shrunken centroids the two classes for features surviving the threshold for at least one class
pamr.plotcen(pam_model, train.dat, t0)
#pamr.plotcen(pam_model, train.dat, t1)

#confusion matrix
pamr.confusion(pam_model.cv, t0)
#pamr.confusion(pam_model.cv, t1)

#visually inspect to see how clearly the classes are seperated by pam
#this is a plot of the cross validation probabilities
pamr.plotcvprob(pam_model, train.dat, t0)

#set up our test set in pam format but guess it wants the exprs(TEST)
# dat1 <- exprs(TEST)
# gene_names1 <- featureData(TEST)$gene
# gID1 <- featureNames(TEST)
# sID1 <- sampleNames(TEST)
# labels1 <- TEST$clasLab
# test.dat <- list(x = dat1, y = labels1, genenames = gene_names1, geneid = gID1,sampleid = sID1)

#use pam to predict test set labels
pamr.predict(pam_model, exprs(TEST), t0)
pamr.predict(pam_model, exprs(TEST), t0, type = "posterior")
#check the truth labels
table(TEST$clasLab)
```

```{r}
mapping <- read.csv("~/R/bmi_551_651_final/data/scoring_and_test_set_id_mappings.csv",check.names=FALSE)

kaggle.out <- data.frame()

for(row in 1:nrow(mapping))
{
  kaggle.out <- rbind(kaggle.out,c(mapping[row,"id"],kaggle.classes[mapping[row,"drug"],mapping[row,"cellline"]]))
}
colnames(kaggle.out)<-c('id','value')

fptr <- file(description="~/R/bmi_551_651_final/MarkBeta/SubtypeSVM_out.csv",'w')
write.csv(kaggle.out,fptr,row.names=FALSE, quote = FALSE)
close(fptr)
```
